name: CI

on: [push]

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: php-actions/composer@master
        with:
          php_version: '8.0'

      - uses: php-actions/phpunit@master
        with:
          php_version: '8.0'
          version: 9.6
          bootstrap: vendor/autoload.php
          configuration: phpunit.xml
